config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :herds do
    resources :invite_links, path: 'links'
  end
  resources :users, only: %i[show]

  scope controller: :invite_links do
    get 'join/:code', action: :new_join, as: 'join_herd_invite_link'
    post 'join/:code', action: :create_join
  end

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource :password, only: %i[edit update]
  namespace :identity do
    resource :email, only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset, only: %i[new edit create update]
    get 'settings', to: 'settings#index', as: 'settings'
  end
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/herd.rb
# frozen_string_literal: true

class Herd < ApplicationRecord
  belongs_to :captain, class_name: 'User', optional: false
  has_many :invite_links, dependent: :nullify
  has_many :memberships, class_name: 'HerdMembership', dependent: :destroy
  has_many :members, class_name: 'User', through: :memberships, source: :user, inverse_of: :herds
  has_many :matches, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 },
                   format: { with: /\A[\w\s]+\z/, message: I18n.t('only_allows_letters') }

  after_create do
    members << captain
    save
  end

  def has?(user)
    members.exists?(user.id)
  end
end

app/controllers/herds_controller.rb
# frozen_string_literal: true

class HerdsController < ApplicationController
  before_action :set_herd, only: %i[show edit update destroy]

  # GET /herds or /herds.json
  def index
    @herds = Current.user.herds
  end

  # GET /herds/1 or /herds/1.json
  def show; end

  # GET /herds/new
  def new
    @herd = Herd.new
  end

  # GET /herds/1/edit
  def edit; end

  # POST /herds or /herds.json
  def create
    @herd = Herd.new(herd_params)
    @herd.captain = Current.user

    if @herd.save
      redirect_to herd_url(@herd), notice: I18n.t('herd_was_successfully_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /herds/1 or /herds/1.json
  def update
    if @herd.captain != Current.user
      return redirect_to herd_url(@herd), status: :unprocessable_entity,
                                          notice: I18n.t('you_are_not_the_captain_of_this_herd')
    end

    if @herd.update(herd_params)
      redirect_to herd_url(@herd), notice: I18n.t('herd_was_successfully_updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /herds/1 or /herds/1.json
  def destroy
    @herd.destroy!

    redirect_to herds_url, notice: I18n.t('herd_was_successfully_destroyed')
  end

  private

  def set_herd
    @herd = Herd.find(params[:id])
  end

  def herd_params
    params.require(:herd).permit(:name)
  end
end

app/helpers/herds_helper.rb
# frozen_string_literal: true

module HerdsHelper
end

app/views/herds/_form.html.erb
<%= form_with(model: herd) do |form| %>
  <% if herd.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(herd.errors.count, "error") %> prohibited this herd from being saved:</h2>

      <ul>
        <% herd.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label>
    Name
    <%= form.text_field :name %>
  </label>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/herds/_herd.html.erb
<div id="<%= dom_id herd %>">
  <h3><%= herd.name %></h3>
  <dl>
    <dt>Captain</dt>
    <dd><%= link_to herd.captain %></dd>
  </dl>
</div>

app/views/herds/edit.html.erb
<h1>Editing herd</h1>

<%= render "form", herd: @herd %>

<br>

<div>
  <%= link_to "Show this herd", @herd %> |
  <%= link_to "Back to herds", herds_path %>
</div>

app/views/herds/index.html.erb
<h1>Teams</h1>

<%= turbo_frame_tag :herds, target: '_top' do %>
  <% @herds.each do |herd| %>
    <%= render herd %>
    <p>
      <%= link_to "Show this herd", herd %>
    </p>
  <% end %>
<% end %>

<%= link_to "New herd", new_herd_path %>

app/views/herds/new.html.erb
<h1>New herd</h1>

<%= render "form", herd: @herd %>

<br>

<div>
  <%= link_to "Back to herds", herds_path %>
</div>

app/views/herds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @herd %>

<%= turbo_frame_tag :invite_links, src: herd_invite_links_path(@herd), target: '_top' %>

<div>
  <%= link_to "Edit this herd", edit_herd_path(@herd) %> |
  <%= link_to "Back to herds", herds_path %>

  <%= button_to "Destroy this herd", @herd, method: :delete %>
</div>