config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :herds do
    resources :invite_links, path: 'links'
  end
  resources :users, only: %i[show]

  scope controller: :invite_links do
    get 'join/:code', action: :new_join, as: 'join_herd_invite_link'
    post 'join/:code', action: :create_join
  end

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource :password, only: %i[edit update]
  namespace :identity do
    resource :email, only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset, only: %i[new edit create update]
    get 'settings', to: 'settings#index', as: 'settings'
  end
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/invite_link.rb
# frozen_string_literal: true

class InviteLink < ApplicationRecord
  belongs_to :user
  belongs_to :herd

  validates :expires_at, comparison: { greater_than: Time.zone.now }, presence: true, on: :create
  validates :spaces_remaining, comparison: { greater_than_or_equal_to: 0 }, presence: true

  generates_token_for(:invite_code, expires_in: 1.year) { valid?(:create) }

  after_create do
    if code.blank?
      self.code = generate_token_for :invite_code
      save
    end
  end

  def join(user)
    self.spaces_remaining -= 1
    save!
    herd.members << user
  end
end

app/controllers/invite_links_controller.rb
# frozen_string_literal: true

class InviteLinksController < ApplicationController
  before_action :set_herd, except: %i[new_join create_join]
  before_action :set_invite_link, only: %i[show edit update destroy new_join create_join]

  def index
    @invite_links = @herd.invite_links
  end

  def show
    if @invite_link.user != Current.user
      return redirect_to root_path,
                         alert: I18n.t('you_don_t_have_permission_to_do_that')
    end

    redirect_to join_herd_invite_link_path(@invite_link.code)
  end

  def new_join
    redirect_to root_path, alert: I18n.t('link_was_expired') if @invite_link.nil?
  end

  def create_join
    return redirect_to root_path, alert: I18n.t('link_was_expired') if @invite_link.nil?

    if @invite_link.herd.has?(Current.user)
      return render :new_join, status: :unprocessable_entity,
                               alert: I18n.t('you_already_joined_this_herd')
    end

    @invite_link.join(Current.user)

    redirect_to @invite_link.herd, notice: I18n.t('successfully_joined_herd_with_name', name: @invite_link.herd.name)
  end

  def new
    @invite_link = InviteLink.new
  end

  def edit; end

  def create
    @invite_link = InviteLink.new(invite_link_params)

    @invite_link.user = Current.user
    @invite_link.herd = @herd

    if @invite_link.save
      redirect_to herd_invite_link_path(@herd, @invite_link), notice: I18n.t('invite_link_was_successfully_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @invite_link.update(invite_link_params)
      redirect_to herd_path(@herd), notice: I18n.t('invite_link_was_successfully_updated'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @invite_link.destroy!
    redirect_to herd_invite_links_path(@herd), notice: I18n.t('invite_link_was_successfully_destroyed'),
                                               status: :see_other
  end

  private

  def set_invite_link
    @invite_link = InviteLink.find(params[:id]) if params[:id]
    @invite_link = InviteLink.find_by_token_for(:invite_code, params[:code]) if params[:code]
  end

  def set_herd
    @herd = Herd.find(params[:herd_id])
  end

  def invite_link_params
    params.require(:invite_link).permit(:expires_at, :spaces_remaining)
  end
end

app/helpers/invite_links_helper.rb
# frozen_string_literal: true

module InviteLinksHelper
end

app/views/invite_links/_form.html.erb
<%# locals: (herd:, invite_link:) -%>

<%= form_with(model: [herd, invite_link]) do |form| %>
  <% if invite_link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invite_link.errors.count, "error") %> prohibited this invite_link from being saved:</h2>

      <ul>
        <% invite_link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label>
    Expires At
    <%= form.date_field :expires_at, value: Time.now + 30.days %>
  </label>

  <label>
    Spaces Remaining
    <%= form.number_field :spaces_remaining %>
  </label>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invite_links/_invite_link.html.erb
<div id="<%= dom_id invite_link %>">
  <%= invite_link.code %>

  <%= button_to herd_invite_link_path(invite_link.herd, invite_link), method: :delete do %>
    <i class="ph-fill ph-trash"></i>
  <% end %>

  <%= link_to "Edit this invite link", edit_herd_invite_link_path(invite_link.herd, invite_link) %>
</div>

app/views/invite_links/edit.html.erb
<h1>Editing invite link</h1>

<%= render "form", herd: @herd, invite_link: @invite_link %>

<br>

<div>
  <%= link_to "Show this invite link", herd_invite_link_path(@herd, @invite_link) %> |
  <%= link_to "Back to invite links", herd_invite_links_path(@herd) %>
</div>

app/views/invite_links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Invite links</h1>

<%= link_to 'Back to herd', @herd %>

<%= turbo_frame_tag :invite_links, target: '_top' do %>
  <% @invite_links.each do |invite_link| %>
    <%= render invite_link %>
    <p>
      <%= link_to "Show this invite link", herd_invite_link_path(@herd, invite_link) %>
    </p>
  <% end %>
  <%= link_to "New invite link", new_herd_invite_link_path %>
<% end %>

app/views/invite_links/new.html.erb
<h1>New invite link</h1>

<%= render "form", herd: @herd, invite_link: @invite_link %>

<br>

<div>
  <%= link_to "Back to invite links", herd_invite_links_path(@herd) %>
</div>

app/views/invite_links/new_join.html.erb
<h2>Join <%= @invite_link.herd.name %></h2>
<p>
  You were invited by <%= @invite_link.user.username %>. Remaining: <%= pluralize @invite_link.spaces_remaining, 'space' %>
</p>
<%= button_to 'Join', join_herd_invite_link_path(@invite_link.code), method: :post %>