config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :herds do
    resources :invite_links, path: 'links'
  end
  resources :users, only: %i[show]

  scope controller: :invite_links do
    get 'join/:code', action: :new_join, as: 'join_herd_invite_link'
    post 'join/:code', action: :create_join
  end

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource :password, only: %i[edit update]
  namespace :identity do
    resource :email, only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset, only: %i[new edit create update]
    get 'settings', to: 'settings#index', as: 'settings'
  end
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_header.html.erb
<header>
  <%= link_to root_path do %>
    <h1>
      <i class="ph-fill ph-cow"></i>
      Vachinator
    </h1>
  <% end %>

  <nav>
    <% if Current.user %>
      <%= Current.user.username %>
      <%= button_to "Try Log out", Current.session, method: :delete %>
    <% else %>
      <%= button_to "Try Sign in", sign_in_path, method: :get %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Precise</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

  <link
    rel="stylesheet"
    type="text/css"
    href="https://unpkg.com/@phosphor-icons/web@2.1.1/src/fill/style.css"
    />

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render 'layouts/header' %>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<main>
  <%= yield %>
</main>
</body>
</html>